backend = "glx";
vsync = true;

corner-radius = 15;

rules = (
  # Fade windows that aren't focused
  { match = "window_type = 'normal' && !focused"; opacity = 0.85; },
  # Corner radius for the bar
  { match = "window_type = 'dock'"; corner-radius = 15; },
);
